---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-server
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns
      chart: kiali-server
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: kaili-charts
        namespace: flux-system
      interval: 5m
  values:
    auth:
      strategy: "anonymous"
