---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns
      chart: kiali-server
      version: 1.52.0
      sourceRef:
        kind: HelmRepository
        name: kiali-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    auth:
      strategy: "anonymous"
    istio_namespace: istio-system
      prometheus-prometheus
    external_services:
      prometheus:
        url: "http://prometheus-prometheus.monitoring.svc.cluster.local:9090/"
      grafana:
        enabled: true
        in_cluster_url: 'http://grafana.monitoring.svc.cluster.local:3000/'
        # Public facing URL of Grafana
        url: 'https://grafana.${INTERNAL_DOMAIN}/grafana'
