---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard
  - helmrelease.yaml
namespace: network
configMapGenerator:
  - name: blocky-whitelist
    files:
      - whitelist.txt
generatorOptions:
  disableNameSuffixHash: true
