---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: hashicorp
spec:
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: consul
      version: 0.43.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
      interval: 5m
  values:

    global:
      enabled: true
      logLevel: debug

      image: "hashicorp/consul:1.12.0"
      imageK8S: "hashicorp/consul-k8s:0.26.0"
      # Rate limiting be damned
      # imagePullSecrets:
      #  - name: regcred
      datacenter: dc1

      server:
        enabled: "true"
        replicas: 3
      service:
        enabled: true
        type: loadBalancer
        additionalSpec: |
        loadBalancerIP: ${SVC_CONSUL_ADDR}
      ports:
        serflan:
          port: 8301

      storage: 100Gi
      storageClass: longhorn
      ingress:
        enabled: true
        ingressClassName: nginx
        pathType: Prefix
        hosts:
          - host: consul.${INTERNAL_DOMAIN}
            paths:
              - /
        tls:
          - secretName: secret-consul-tls
          - hosts:
              - consul.${INTERNAL_DOMAIN}
      hostNetwork: true
