---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesg
  namespace: chaos-mesh
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/external-dns
      chart: chaos-mesh
      version: v2.2.0
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh-charts
        namespace: flux-system
      interval: 5m
  values:
    # clusterScoped is whether chaos-mesh should manage kubernetes cluster wide chaos
    # Also see rbac.create and controllerManager.serviceAccount
    clusterScoped: true

    # Creating rbac API Objects. Also see clusterScoped and controllerManager.serviceAccount
    rbac:
      create: true
