---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-v1
  namespace: dev
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
