---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-v1
  namespace: home
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
