apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home
stringData:
    HASS_MARIADB_PASSWORD: ENC[AES256_GCM,data:tKwQdL64PE9rZQ4=,iv:3zmqin/Cb8ZnoDCdkMUQd9bUw9SLkmlvKAtljt3PqNs=,tag:9uOh3WVzufpJ+1nmpZC2mg==,type:str]
    HASS_MARIADB_USERNAME: ENC[AES256_GCM,data:A5aTrk2qvwk4rI/gSsQ=,iv:EjSkOWpIgxQQbPQsXf8qVVI2QK0LDRKED7Gw8b43FjI=,tag:t3MCY9d+5gU5R1nyCsXr7Q==,type:str]
    HASS_MQTT_PASSWORD: ENC[AES256_GCM,data:mKaBdvYAw+ai,iv:iSU8Gav4VkPi/ruNffQ/bIVaZTL9af3W3J6Qylc1m1s=,tag:kF9N5x7rd/n8Joaq2plBYQ==,type:str]
    HASS_MQTT_USERNAME: ENC[AES256_GCM,data:uTr3+g==,iv:4HOxn4rdkgIeu6Q59g02votOh8yCmZC44vob3yUKEEs=,tag:h1+Qay8gluaOyJnKBMikTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSEU0TmtzZ0t6ck5xS1ZM
            R3J6UTNkVzFVMDhtZ2E5MlRSUUR3UzQ2QlQ0ClRqMTlzeW9DMkJORXRCaDdMcjJB
            YzlmYWxYaUxNK2kyOEF0M29ud0R4UmcKLS0tIDRlRXk2eWdGQ241RXg2SDluVW1G
            OE5HeUlnRUZid1hJZjNCeUU1OVpjSzgKsQ/K/SkkBaccZYZb/81anadj9XWQ2I8X
            AUVWR2G8uNvHenISmqmUnyVDHhME6BmfwNG6QkBhSUTgdtPI7mCc2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-11T13:14:40Z"
    mac: ENC[AES256_GCM,data:et/r3l1EXARqIb9clwgEZjwTIs3CfQ0W4bP9gJEZdm8Rvn+7++Eisl1+BnFGOHnm1618lHkdk1iySnbR7KHx60TuTnRi4jNwKZSPeFEAsIid6kffHexD/4Q2LeImIqUWs/mhOSvbluctIA7ujHJkABhS54QX4cz22ErDUzxdi0g=,iv:YFYAUEtVJjiBuxEILVcT0sF4Vc+CJH5JpUBvvp7BJqg=,tag:Nl8Jcv9YaM3RBJrxinYpDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
