---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-v1
  namespace: home
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
