---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
