---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wireguard
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: wireguard
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/wireguard
      tag: v1.0.20210424
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "wireguard.${INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "wireguard.${INTERNAL_DOMAIN}"
          - secretName: wrieguard-tls
    podSecurityContext:
      fsGroup: 0
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: wireguard-config
        mountPath: /etc/wireguard
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
