---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dags-pvc.yaml
  - helmrelease.yaml
  - logs-pvc.yaml
  - airflow-ssh.secrets.sops.yaml
  - airflow.secrets.sops.yaml
  - airflow-git.secrets.sops.yaml
  # - airflow-metadata.secrets.sops.yaml
