---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-v1
  namespace: dev
  labels:
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
