---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  dependsOn:
    - name: metallb
      namespace: metallb-system
    - name: istio-base
      namespace: istio-system
  maxHistory: 3
  interval: 1m0s
  suspend: false
  releaseName: istio-gateway
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: gateway
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system

  values:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: ${SVC_ISTIOGATEWAY_ADDR}
