---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jenkins.io
      chart: jenkins
      version: 3.12.1
      sourceRef:
        kind: HelmRepository
        name: jenkins-charts
        namespace: flux-system
      interval: 5m

  values:

    controller:
      image: "jenkins/jenkins"
      tag: 2.330-jdk11
      tagLabel: jdk11
      imagePullPolicy: IfNotPresent
      numExecutors: 2
      admin:
        existingSecret: "jenkins"
        userKey: jenkins-admin-user
        passwordKey: jenkins-admin-password

    initializedOnce: true

    # Their ingress is a mess, I'll use my own.
    ingress:
      enabled: false

    podSecurityContextOverride:
      runAsUser: 1000
      runAsNonRoot: false
      supplementalGroups: [1000]
      capabilities: {}

    agent:
      enabled: true
      image: "jenkins/inbound-agent"
      tag: "4.11-1"

    persistence:
      enabled: true
      existingClaim: jenkins-pvc-v1
