---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.5.8
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: flux-system

  values:

    replicaCount: 3
    image:
      repository: "pihole/pihole"
      tag: "2022.01.1"
      pullPolicy: IfNotPresent

    serviceDns:
      type: LoadBalancer
      loadBalancerIP: ${SVC_PIHOLE_ADDR}

    serviceDhcp:
      type: LoadBalancer

    ingress:
      ingressClassName: nginx
      enabled: true
      hosts:
        - pihole.192.168.2.50.nip.io

    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteMany
      size: "10G"
      storageClassName: "longhorn"

    adminPassword: ${SECRET_PASSWORD}
    DNS1: "1.1.1.1"
    DNS2: "8.8.8.8"
