---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces
  - metallb-system
  - cert-manager
  - ingress-nginx
  - longhorn
  - external-dns
  - k8s-dashboard
  - system
  # - authentik
  - hashicorp
  - kube-system
