apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EMAIL: ENC[AES256_GCM,data:lm+B6LTuwk897duWkvmQhY1y,iv:hHHHBr1fdZGqISm1I9Fs9XFy4qrOmTK/jdfIvRqaIoM=,tag:lWUeBvYr7Prdx2V6X/bP9Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BM2dNAcB/s+P4Cdkgoo=,iv:1hZNREqGvK1iprMUT0u5+N5dpXHABU6Esgzfg5cEmoc=,tag:jztQFFCoPHIwP8NxqCrgJw==,type:str]
    SECRET_DOMAIN2: ENC[AES256_GCM,data:77WImCCY5Z3C8EpkOg==,iv:vJLsSO2bjM5X9Ssp8tkKBUzripLrYFvyiY7ulDEypU0=,tag:N45dFFxjmMoueGD7i3qJfQ==,type:str]
    SECRET_DOMAIN3: ENC[AES256_GCM,data:El0GvlfoCDTUNLnErAk=,iv:QzNEQ2OGrkSMSHlxpx3R0QTOpSwiGIUxXuQ0k6/C3+A=,tag:V/4UYoQTZaanp7nMfCIydw==,type:str]
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:vLaat5hb+ZbwbNabgzz7Pu1PyQ==,iv:BP1OMI+Ii9Rtd02XuXD1j5qHjd+nQ25IU/lXLX/kQ2M=,tag:w+Vs1BOEfeKbvCUca+64wg==,type:str]
    ISTIO_DOMAIN: ENC[AES256_GCM,data:C9r1jo62HFjSirg8cFCtvbmg7Q==,iv:0sgu10T2vQY1iq5gg+DaVs4bXu4wjB9jxcsNbi43lZ4=,tag:GprlPKrJhjFrRW+GIz47Bg==,type:str]
    VALHEIM_SERVER: ENC[AES256_GCM,data:HqNH2qXV9/hnb4XG,iv:6llkME0v3nKybba3xhhE5zoyLhCnaA4XULIxhF1vz2g=,tag:fh13MYLA8tvor9KEz6/csg==,type:str]
    VALHEIM_WORLD: ENC[AES256_GCM,data:n9iRSJbJ7qoxlMB0,iv:3o785585rwrI8mLX3Y01U1pBskzZioC9MYond8Wc7DI=,tag:Rq+8K6iaGR6ztp3zyw+gyg==,type:str]
    VALHEIM_PASS: ENC[AES256_GCM,data:ZSJkdcVlWZs=,iv:1mhr5LJd0NbowJfOo/iG7zo4dVIilihdfqU3FbBLBZ4=,tag:R0B/DdIMx0EojgEyhAEFpA==,type:str]
    SUPERVISOR_PASS: ENC[AES256_GCM,data:0cCg7NNrxAy9,iv:66WCGr43qRgUcDu4H6TwR+iX1Nh+Dsc4Fx9pM2JyZRI=,tag:/fpNTybOVHNWHjEODa9C4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNlBwVWp4M0xvZnZhWVhR
            T1YvaHFKZ2dvRSsyU3ZObmNNZm1HVnN4MEdvCmxJMm5Xa29PMG0wYmxBemZvYXJk
            b3J5VUdtYUhiQzBUQ2VNUXpIS0dBczgKLS0tIHBIM29zbEFEZ0VVd3VLM3Q2bzFp
            b0IyMVI1K3RyV3IxUmR0YlE2YVRaa1EKP8I5mG9JwOHlVt2/eTFBIJHJ975kGqyE
            95F1d/Y3EQPHcNM1xLMmmfijFFaXzNVymWQ5wnBpmrmo5i3qDPFAzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-21T20:18:59Z"
    mac: ENC[AES256_GCM,data:U0NotP9GDyXaud713kCP9BD6Tzi1AFW/nxEdfg7QLVYWpZRL0GZsorKfVPFc5owe5GDaaRA4vDnDv8dD6ypKWAMSQp62VioyJ50deuFQ5+SfqvdtKjDFmGchCJ6RcWQzXRQewGQqx/dbqLvODJ3/eQEzjrQwux9FteFABKgvTog=,iv:wvAa4lIhHH+wtjA4+AesVYhtkaJJJ0f6ZATIbYv5OSE=,tag:O2hoc+tw9I3WM/+bwUfBDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
