---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvcx
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: longhorn
