---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat
  namespace: rocketchat
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://rocketchat.github.io/helm-charts
      chart: rocketchat
      version: 4.6.1
      sourceRef:
        kind: HelmRepository
        name: rocketchat-charts
        namespace: flux-system
      interval: 5m

  values:

    image:
      repository: registry.rocket.chat/rocketchat/rocket.chat
      version: 4.4.1
      pullPolicy: IfNotPresent

    smtp:
      enabled: false
      username:
      password:
      host:
      port: 587

    mongodb:
      enabled: true
      auth:
        rootPassword: ${ROCKET_DB_ROOT}
        username: ${ROCKET_DB_USR}
        password: ${ROCKET_DB_PASS}
        database: rocketchat
      replicaCount: 1
      persistence:
        enabled: true
        existingClaim: datadir-rocketchat-mongodb-0
      #  storageClassName: longhorn
      #  accessMode: ReadWriteOnce
      #  size: 10G

    persistence:
      enabled: true
      existingClaim: rocketchat-rocketchat
    #  storageClassName: longhorn
    #  accessMode: ReadWriteOnce
    #  size: 20G
