---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitlab
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: gitlab
      version: 3.10.2
      sourceRef:
        kind: HelmRepository
        name: gitlab-charts
        namespace: flux-system
      interval: 5m

  values:

    global:
      hosts:
        domain: chaoticark.net
        https: false
      minio:
        name: minio.chaoticark.net
        https: true

      ingress:
        enabled: true
        apiVersion: "networking.k8s.io/v1"
        annotations:
          kubernetes.io/tls-acme: "true"
          external-dns/is-public: "true"
        configureCertmanager: true
        tls:
          enabled: true
          secretName: gitlab-tls
        class: nginx

        initialRootPassword:
          secret: gitlab-secrets
          key: password

        psql:
          password:
            useSecret: true
            secret: gitlab-secrets
            key: psql-password

        redis:
          password:
            enabled: true
            secret: gitlab-secrets
            key: redis-password
