---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  dependsOn:
    - name: metallb
      namespace: metallb-system
  maxHistory: 3
  interval: 1m0s
  suspend: false
  releaseName: ingress-nginx
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: nginx-charts
        namespace: flux-system

  values:

    # This is to increase rate limit
    # imagePullSecrets:
    #  - name: regcred

    controller:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
