apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: kube-system
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:p671isnmLyDL,iv:h/ht/P5vsVyiThua43kTgsikIRYy+mSJ+dO2NsFDcIY=,tag:PJJ4MbbEAMQlgHusOIiMmQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:yXtqbPA=,iv:LIYi/PoMDiekNXKVYdFd1+HAKCATsrwKEz0V83RaDos=,tag:7LQEdXRuse9FP0HX1rPlng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWm1Zei90VzQ5bm4zeE9G
            K1l5TEs5MndBUVp5UG5aaStNWHZRcTJwc0U4CjI1N3BMd25RdmxuRm1kZ2ErN1Qw
            MVdsYU5yNkNiUGYzTFBsN1JnZzFYM0UKLS0tIGlLL0pubXVtTVVyTE1HdDdTd2Fy
            dzV4SG1UUlZDM3dGZjk5eHF0Mk9BS3cKVCnq1aa21CfJ0aSPi+aEE0q55Irkhl7m
            XkJbVzUnbRZ/qUjzYKfd1jjnhphjOhnnNUAjcwa+sm/Xb4WRAaneAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-21T13:41:41Z"
    mac: ENC[AES256_GCM,data:Pp1hBJ5claf53FfiVEs2s+FJ7TymdF/JlYx1SViKuY1kAoIZyuPWLxSFXx2xOpF8sdWlVfpmrenkQjonrjy9O/csnXdaZudNVgLfWFkZfX1sY/WDhmL4wgIxXTUG2H1iFve0kWsmygVnr6R0nilCu23AsG74MSBl5wxz02Gv9wU=,iv:visYWSnYDN9fXOIdGipSgsCNnO4vbj9Szx30Z7NFoqY=,tag:nroO23mXjg6151NciQkUcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
