---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.13.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured
        namespace: flux-system
  values:

    image:
      repository: weaveworks/kured
      tag: "1.9.1"
      pullPolicy: IfNotPresent
    updateStrategy: RollingUpdate
    configuration:
      timeZone: America/New_York
      startTime: 2am
      endTime: 5am
    #  notifyUrl: ${KURED_DISCORD_WEBHOOK_URL}
    metrics:
      create: true
