---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-data
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: longhorn
