---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: temp
  namespace: gaming
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sabnzbd
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: lscr.io/linuxserver/sabnzbd
      tag: latest
    env:
      TZ: "America/New_York"
    podSecurityContext:
      supplementalGroups:
        - 100
    persistence:
      mount1:
        enabled: true
        existingClaim: valheim-config
        mountPath: /valheim/config
      mount2:
        enabled: true
        existingClaim: valheim-data
        mountPath: /valheim/data
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
