# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOWV4VXhvQXAzbjhpbVlm
            ZWNBNXl0cEgvUnd5RFViTHhmOFFUYkh0dFZBCjBsQ1ZHVy8wYUt1a3dleGxpL2d4
            MWk3aVZoaUE5YXVVWEpJOUUzMngvMlEKLS0tIFNxNHo1VThuRFB2RDhpSTZRTm5w
            ZHE4SWRHbGRHMVpOQzJQTURZZDQ3cDAKCEh24hexDOH4ACPWynYeqtwfrfIuhfOS
            7Lg/6ff1vgWaSs8C7iQitpRNUtD46e9IfvZ5eJMdUej67OSZP9uSTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-01T12:12:54Z"
    mac: ENC[AES256_GCM,data:+RbWLFjY0rpR4jFBmUxQV4oHeBI7muazSPVcsbnWtq0iktAbfMjz1kCclaOvpmcke9Jo5xDDicb4vewkOUxsm0NUZB15vBbqNPMkJh+udyUFguayfY+2zKFBNTzFISJ25TV5uRKfhAMCcyu2pZT13IDJ+tMmzfG1zybFdRNM14E=,iv:VjMrwMAzHrHwzla+Rl5vqEE8a4ElDIhoxp9CMcGnipE=,tag:8PdVCC267s/jaFVgAqNZ0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
