apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:rGV0Etb5AiCwDiloUcxOY9Cz,iv:UARHrJ5ZT4IawGMXFqhzZl7GsnRwMhAZUYE1nXMfb70=,tag:3/+BCkFrsC/w+9PHeZfVyQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:9gQLPBBA8x9EiAMs317NEYyj2AO8VGlT8k+/KtuagvV46UqKYw==,iv:ij8K88Xk60yzt1NcX8oua41m93aK1Hff/CDyRdZZiSA=,tag:L2hiUN93ntriCamn8Ef/9w==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:hibi9ILLw9Vlytjy8sWKE5uupZXNQEugPGPjF/sdn3E=,iv:AvVcylG3G0hxurwgRhWXz3T+QLJPAWYW16Fc5z8NzjU=,tag:fchGiTVKUJ72vqijqTHI5w==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:IJ7fJka6ovvcIO07/zI=,iv:L5+hJXvgafTMl0pXtCTQx4O/4ShYv46EFFljnAH3zdE=,tag:Me5yMlOWUHS3HR8JjdPG7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pqmv9umk70z2xyv8vvlma070d9rzr02j3ye8gjyv64ddf0sfwccspwsj8d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQ3M2TFFjbnp1S0ZhZjFy
            b2kxU0YyTldNQ21yeEVlVGZJL2ZSZ21xcXlzCnJHWFBaNlJwRGFDbHBkMjlxa3Ux
            NVJjcDVVVTErTjhENStINGhoK0x4QUUKLS0tIHI4YVBCZGVUOGVKSWpwbVFMbUhN
            TDRPMmd1TlhlSkttMWdldStPVUo5MW8KSyRGYJVS17lwZFvMuK6lBpEhOzkbnNWN
            kNZ3JsQdsAxfAZgWED+2Q8+ynNbsy7Z3+K9gWmVcggfLyP44fIYq1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-27T18:30:02Z"
    mac: ENC[AES256_GCM,data:2uNFf/tkw9ZBlrii8M/TNEGVRW1TF25A50vYghuMmgljkpSSGiaC+uFES2JdQBxgIqDb6vPUuRTu1pCgi+n76rnwX+5BXIMFqJANMXDnAqLlhSmDGRiaZOwEh+cgTe+R9W8YQYtPiSA+F1h5B+mH+hytS/v+D0UE/GcbX93msfo=,iv:Ez5FcBeJ0E6mrg0RzxR+9ls8+jvjey98TRD6/ED6gyk=,tag:ZuTJEzsHAKvZ7qAcNlDzFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
