---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  maxHistory: 3
  interval: 1m0s
  suspend: false
  releaseName: istiod
  chart:
    spec:
      # renovate: registryUrl=https://istio-release.storage.googleapis.com/charts
      chart: istiod
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: istio-charts
        namespace: flux-system

  values:
    pilot:
      autoscaleEnabled: true
      autoscaleMin: 1
      autoscaleMax: 5
      replicaCount: 1
      rollingMaxSurge: 100%
      rollingMaxUnavailable: 25%
